INCLUDE "lib/hardware.asm"

STACK_SIZE EQU $80 ; In words, not bytes

JOY_START_BIT  EQU 7
JOY_SELECT_BIT EQU 6
JOY_B_BIT      EQU 5
JOY_A_BIT      EQU 4
JOY_DOWN_BIT   EQU 3
JOY_UP_BIT     EQU 2
JOY_LEFT_BIT   EQU 1
JOY_RIGHT_BIT  EQU 0

JOY_START  EQU 1 << JOY_START_BIT
JOY_SELECT EQU 1 << JOY_SELECT_BIT
JOY_B      EQU 1 << JOY_B_BIT
JOY_A      EQU 1 << JOY_A_BIT
JOY_DOWN   EQU 1 << JOY_DOWN_BIT
JOY_UP     EQU 1 << JOY_UP_BIT
JOY_LEFT   EQU 1 << JOY_LEFT_BIT
JOY_RIGHT  EQU 1 << JOY_RIGHT_BIT

TILEATTR_NONSOLID EQU 0<<0
TILEATTR_SOLID    EQU 1<<0

RSRESET
DEF MAP_SPAWN_X      RB 1
DEF MAP_SPAWN_Y      RB 1
DEF MAP_TILE_DATA    RB SCRN_X_B * SCRN_Y_B
DEF sizeof_MAP_ATTRS RB 0

DEF DIR_NONE  EQU -1
DEF DIR_UP    EQU 0
DEF DIR_RIGHT EQU 1
DEF DIR_DOWN  EQU 2
DEF DIR_LEFT  EQU 3

DEF AXIS_BIT_HORIZONTAL EQU 0
DEF AXIS_BIT_VERTICAL EQU 1

DEF AXIS_HORIZONTAL EQU 0
DEF AXIS_VERTICAL   EQU 1

DEF PLAYER_MOVE_SPEED EQU 16
DEF NUM_SUBPIXEL_BITS EQU 5
